version: '3.3'

services:
  order-service:
    restart: unless-stopped
    build: .
    ports:
      # localhost:docker
      - "8100:9102"
    depends_on:
      - db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./config.yaml:/config.yaml
    entrypoint: sh -c "Order-Service migrate up && Order-Service run service"


  db:
    image: postgres
    restart: always
    ports:
      # localhost:docker
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/pgdata
      - ENSUREDB=1
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
