openapi: 3.0.0
info:
  version: 1.0.0
  title: order-service
  description: ''
servers:
  - url: 'https://api.demo.tokend.io'
    description: TokenD Developer Environment
security:
  - bearerAuth: []
